name: dasubtitle
description: Subtitle help tool
version: 1.0.3
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  path: ^1.8.2
